#!/bin/sh
#
# Loads required hardware modules
#

start() {
	printf "Starting hardware handling: "
	modprobe cdc_acm # Arduino
	modprobe pl2303 # USB↔Serial cable
	# I2C
	modprobe i2c-bcm2708 # RPi2
	modprobe i2c-bcm2835 # RPi3
	modprobe i2c-dev # Both
	/opt/chef/lcdOff.sh
	echo "OK"
}

stop() {
	printf "Stopping hardware handling: "
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
