#!/bin/sh
#
# Changes keyboard layout to AZERTY
#

start() {
	printf "Starting AZERTY keyboard: "
	loadkmap < /usr/share/keyboard/fr-latin9.bmap
	echo "OK"
}

stop() {
	printf "Stopping AZERTY keyboard: "
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
