#!/bin/sh
#
# Connect to Wi-Fi network
#

start() {
	printf "Starting Wi-Fi connection: "
	# modprobe brcmfmac
	modprobe r8188eu
	ifup wlan0
	echo "OK"
}

stop() {
	printf "Stopping Wi-Fi connection: "
	ifdown wlan0
	# rmmod brcmfmac
	rmmod r8188eu
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
